import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { Row, Col, Breadcrumb } from 'antd'
import { CalendarTwoTone, StarTwoTone } from '@ant-design/icons'
import Header from '../components/Header'
import Author from '../components/Author'
import Advert from '../components/Advert'
import Footer from '../components/Footer'
import BreadcrumbItem from 'antd/lib/breadcrumb/BreadcrumbItem'
const Detailed = () => (
  <>
    <Head>
      <title>文章详情</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <Row className="comm-main" type="flex" justify="center">
      <Col className="comm-left" xs={24} sm={24} md={16} lg={18} xl={14}  >
        <div>
          <div className="bread-div">
            <Breadcrumb>
              <BreadcrumbItem>
                <Link href="/">
                  <a>首页</a>
                </Link>
              </BreadcrumbItem>
              <BreadcrumbItem>
                <Link href="/">
                  <a>文章列表</a>
                </Link>
              </BreadcrumbItem>
              <BreadcrumbItem>
                <Link href="/">
                  <a>文章名xxx</a>
                </Link>
              </BreadcrumbItem>
            </Breadcrumb>
          </div>
          <div>
            <div className="detailed-title">
              甜沁的博客文章--title
            </div>
            <div className="list-icon center">
              <span>
                <CalendarTwoTone />2021-10-20
              </span>
              <span>
                <StarTwoTone />类别
              </span>
            </div>
            <div className="detailed-content">
                这里用于展示文章的内容
            </div>
          </div>
        </div>
      </Col>

      <Col className="comm-right" xs={0} sm={0} md={7} lg={5} xl={4}>
        <Author/>
        <Advert/>
      </Col>
    </Row>
    <Footer></Footer>
  </>
)

export default Detailed