import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { Row, Col, Breadcrumb,Affix} from 'antd'
import { CalendarTwoTone, StarTwoTone } from '@ant-design/icons'
import Header from '../components/Header'
import Author from '../components/Author'
import Advert from '../components/Advert'
import Footer from '../components/Footer'
import BreadcrumbItem from 'antd/lib/breadcrumb/BreadcrumbItem'
import marked from 'marked'
import hljs from 'highlight.js'
import Tocify from '../components/tocify.tsx'
import MarkNav from 'markdown-navbar';
import Axios from 'axios'
import servicePath from '../config/apiUrl'
const Detailed = (props) => {
  const tocify = new Tocify()
  const renderer = new marked.Renderer()

  renderer.heading = function(text, level, raw) {
    const anchor = tocify.add(text, level)
    return `<a id="${anchor}" href="#${anchor}" class="anchor-fix">
              <h${level}>${text}</h${level}>
           </a>\n`
  }
  marked.setOptions({
    renderer: renderer,
    gfm: true,
    pedantic: false,
    sanitize: false,
    tables: true,
    breaks: false,
    smartLists: true,
    highlight: function(code) {
      return hljs.highlightAuto(code).value
    }
  })
  let html = marked(props.article_content) 
  return (
    <>
      <Head>
        <title>文章详情</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Row className="comm-main" type="flex" justify="center">
        <Col className="comm-left" xs={24} sm={24} md={16} lg={18} xl={14}  >
          <div>
            <div className="bread-div">
              <Breadcrumb>
                <BreadcrumbItem>
                  <Link href="/">
                    <a>首页</a>
                  </Link>
                </BreadcrumbItem>
                <BreadcrumbItem>
                  <Link href={{pathname:'/list',query:{id:props.id}}}>
                    <a>文章列表</a>
                  </Link>
                </BreadcrumbItem>
                <BreadcrumbItem>
                  <Link href="#">
                    <a> {props.title}</a>
                  </Link>
                </BreadcrumbItem>
              </Breadcrumb>
            </div>
            <div>
              <div className="detailed-title">
               {props.title}
              </div>
              <div className="list-icon center">
                <span>
                  <CalendarTwoTone />{props.addTime}
                </span>
                <span>
                  <StarTwoTone />{props.typename}
                </span>
              </div>
              <div className="detailed-content"
               dangerouslySetInnerHTML={{__html:html}}
              >
              </div>
            </div>
          </div>
        </Col>

        <Col className="comm-right" xs={0} sm={0} md={7} lg={5} xl={4}>
          <Author />
          <Affix offsetTop={5}>
            <div className="detailed-nav comm-box">
            <div className="nav-title">文章目录</div>
              {
                tocify && tocify.render()
              }
          </div>
          </Affix>
        </Col>
      </Row>
      <Footer></Footer>
    </>

  )
}
Detailed.getInitialProps = async (context) => {
  let id = context.query.id
  const promise = new Promise((reslove) => {
    Axios(servicePath.getArticleById + id)
     .then((res) => {
       console.log(res)
       reslove(res.data.data[0])
     })
  })

  return await promise
}

export default Detailed