import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React, {useState} from 'react'
import {Row, Col, List, Button} from 'antd'
import {
  BookTwoTone,
  DashboardTwoTone
} from '@ant-design/icons'
import Header from '../components/Header'
import Author from '../components/Author'
import Footer from '../components/Footer'
import Advert from '../components/Advert'
import axios from 'axios'
import servicePath from '../config/apiUrl'
 const Home = (list)=> {
  
  const [mylist, setMylist] = useState(list.data)
  console.log(list.data)
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Row className="comm-main" type="flex" justify="center">
        <Col className="comm-left" xs={24} sm={24} md={16} lg={18} xl={14}  >
          <List
            header={<div>最新日志</div>}
            itemLayout="vertical"
            dataSource={mylist}
            renderItem={item => (
              <List.Item>
                <div className="list-title">
                  <Link href={{pathname:'/detailed', query:{id:item.id}} }>
                   <a>{item.title}</a> 
                  </Link>           
                </div>
                <div className="list-icon">
                  <p><DashboardTwoTone />  {item.addtime}</p>
                  <p><BookTwoTone /> {item.typename}</p>
                </div>
                <div className="list-context">{item.introduce}</div>
              </List.Item>
            )}
          />
        </Col>
        <Col className="comm-box" xs={0} sm={0} md={7} lg={5} xl={4}>
          <Author></Author>
          <Advert></Advert> 
        </Col>
      </Row>
      <Footer></Footer>
    </div>
  )


}
Home.getInitialProps = async () => {

  const promise = new Promise((reslove) => {
      axios(servicePath.getArticleList)
      .then( res => {
        console.log('res',res.data)
        reslove(res.data)
      })
  })
  return await promise
}

export default Home