import Head from 'next/head'
import Image from 'next/image'
import React, {useState} from 'react'
import { Button } from 'antd'
import {Row, Col, List} from 'antd'
import {
  BookTwoTone,
  DashboardTwoTone
} from '@ant-design/icons'
import Header from '../components/Header'
import Author from '../components/Author'
import Footer from '../components/Footer'

const MyList = () => {
  const [mylist, setMylist] = useState(
    [
      {title:'文章例子标题1',context:'考研的第一步就是确定目标专业，因为不同专业的考试科目有区别。不清楚考试科目内容，盲目复习容易浪费时间。今天给大家分享一下英语一及英语二的区别：'},
      {title:'这是第二个测试标题',context:'考研的第一步就是确定目标专业，因为不同专业的考试科目有区别。不清楚考试科目内容，盲目复习容易浪费时间。今天给大家分享一下英语一及英语二的区别：'},
      {title:'哎呀好烦标题应该叫什么才好',context:'考研的第一步就是确定目标专业，因为不同专业的考试科目有区别。不清楚考试科目内容，盲目复习容易浪费时间。今天给大家分享一下英语一及英语二的区别：'},
      {title:'我是在不知道例子的标题该怎么写',context:'考研的第一步就是确定目标专业，因为不同专业的考试科目有区别。不清楚考试科目内容，盲目复习容易浪费时间。今天给大家分享一下英语一及英语二的区别：'},
    ]
  )
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Row className="comm-main" type="flex" justify="center">
      <Col className="comm-left" xs={24} sm={24} md={16} lg={18} xl={14}  >
      <List
        header={<div>最新日志</div>}
        itemLayout="vertical"
        dataSource={mylist}
        renderItem={item => (
          <List.Item>
            <div className="list-title">{item.title}</div>
            <div className="list-icon">
              <p><DashboardTwoTone />  2019-06-28</p>
              <p><BookTwoTone />  文章类别</p>
            </div>
            <div className="list-context">{item.context}</div>  
          </List.Item>
    )}
  />    
      </Col>

      <Col className="comm-box" xs={0} sm={0} md={7} lg={5} xl={4}>
      <Author></Author>
      </Col>
    </Row>
    <Footer></Footer>
    </div>
  )
}

export default MyList